/oakd:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: false
      i_pipeline_type: RGBStereo
      i_nn_type: none
      i_usb_speed: SUPER_PLUS
    rgb:
      i_board_socket_id: 0
      i_fps: 30.0
      i_height: 720
      i_interleaved: false
      i_max_q_size: 10
      i_preview_size: 250
      i_enable_preview: false
      i_low_bandwidth: false
      i_keep_preview_aspect_ratio: true
      i_publish_topic: true
      i_resolution: '720'
      i_width: 1280
      r_focus: 1
      r_set_man_focus: true
    stereo:
      i_reverse_stereo_socket_order: true
      i_align_depth: true
      i_subpixel: true
      i_publish_left_rect: true
      i_publish_right_rect: true
      i_publish_synced_rect_pair: true
    left:
      i_resolution: '400'
      i_fps: 30.0
    right:
      i_resolution: '400'
      i_fps: 30.0
    use_sim_time: false
